apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ehus0ev2f-nodejs
  janus-idp.io/tekton: ehus0ev2f-nodejs
  backstage.io/kubernetes-id: ehus0ev2f-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ehus0ev2f-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
